version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: is-he-online-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: is-he-online-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TARGET_USER_ID=${TARGET_USER_ID}
      
      # Server Configuration
      - PORT=3000
      - NODE_ENV=production
      
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      
      # API Security
      - API_KEY=${API_KEY}
    
    depends_on:
      redis:
        condition: service_healthy
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for necessary writable directories)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
# Named volumes for persistent data
volumes:
  redis_data:
    driver: local
